### ISSUE TITLE
The cpt tool is broken

### ISSUE THREAD

**Issue by dclong** [root-project/cling#347]
![image](https://user-images.githubusercontent.com/824507/84225577-5c618c80-aa94-11ea-96f2-e8bf334b2549.png)

**Comment by reikdas** [comment]
https://github.com/root-project/root/pull/5834 should fix it :)

**Comment by reikdas** [comment]
> [root-project/root#5834](https://github.com/root-project/root/pull/5834) should fix it :)

The commit is in Cling master now. 
@dclong Can you please checkout the latest commits from master and try?

**Comment by dclong** [comment]
Still encounter issues.

![image](https://user-images.githubusercontent.com/824507/84451066-c9952f00-ac06-11ea-902b-e0f1fe0d0e14.png)

**Comment by reikdas** [comment]
The error message implies that cpt does not support building Cling using an LLVM binary on your system. Try without the `--with-binary-llvm` and `--with-llvm-tar` flags.

**Comment by dclong** [comment]
The command I run was `python3 cpt.py --check-requirements -y`. I didn't use the options `--with-binary-llvm` and `--with-llvm-tar`. How can disable that? Also, can `cpt.py` print hints to users on what option to use to fix the problem?

**Comment by reikdas** [comment]
@dclong Can you try from the latest master now? The problem should be fixed :)

> Also, can cpt.py print hints to users on what option to use to fix the problem?

Thanks for the suggestion - I incorporated it into cpt :)

**Comment by dclong** [comment]
It seems to working now. Thank you!
