### ISSUE TITLE
Definition shadowing prevents template specialization

### ISSUE THREAD

**Issue by SylvainCorlay** [root-project/cling#359]
With the following code showing template specialization

```cpp
#include <typeinfo>

template <class T>
class FooT
{
public:
    
    explicit FooT(const T& t) : m_t(t) {}
    
    void print() const
    {
        std::cout << typeid(T).name() << " m_t = " << m_t << std::endl;
    }
    
private:
    
    T m_t;
};

template <>
class FooT<int>
{
public:
    
    explicit FooT(const int& t) : m_t(t) {}
    
    void print() const
    {
        std::cout << "m_t = " << m_t << std::endl;
    }
    
private:
    
    int m_t;
};

FooT<double> foot1(1.2);
```

Cling complains about undeclared identifiers.

```
input_line_35:2:2: error: use of undeclared identifier 'FooT'
 FooT<double> foot1(1.2);
 ^
input_line_35:2:13: error: expected '(' for function-style cast or type construction
 FooT<double> foot1(1.2);
      ~~~~~~^
input_line_35:2:15: error: type 'FooT<double>' does not provide a call operator
 FooT<double> foot1(1.2);
              ^~~~~
```

**Comment by Axel-Naumann** [comment]
@jalopezg-uc3m comments? :-)

**Comment by jalopezg-uc3m** [comment]
PR #6571 solves this as a side-effect, but it is still work in progress.  :-)

**Comment by SylvainCorlay** [comment]
@jalopezg-r00t should we close this then?

**Comment by jalopezg-r00t** [comment]
Hello @SylvainCorlay,

Yes, sorry, I forgot to close this issue.  The fix is already part of the master branch; the problem should be fixed there.  :-)  Thanks for reporting.

Cheers,
J.

**Comment by SylvainCorlay** [comment]
This is great thanks!

Would you consider tagging a 0.7.1 release with the latest fixes?

**Comment by SylvainCorlay** [comment]
Hey @jalopezg-r00t FYI, this issue is still occuring with cling 0.8.

Definition shadowing prevents template specialization.

I think we should re-open that issue.

**Comment by jalopezg-r00t** [comment]
Thanks for reporting, @SylvainCorlay!  I will take a look again!

**Comment by jalopezg-r00t** [comment]
Hello @SylvainCorlay,

The example above works for me with cling-0.8.  The only required change is to add `#include <iostream>`, as it is required to use `std::cout`.

Can you please provide an example that make it fail?

Cheers.

**Comment by SylvainCorlay** [comment]
Apologies. Somehow, the build of xeus-cling on conda picked up 0.7. Closing again.
